#-------------------------------
# Site Settings
title: Brian Beyond
description: A place to capture memories and experiences from adventures around the world. Mountains, marathons, global adventures and big goals. All documented here to share the preparation, lessons, and moments that make the journey meaningful. Follow for stories of adventure racing, kayaking, mountaineering, running, thru-hiking, triathlon, world travel & off the trail adventures. 
logo: '/images/logolight.png'
logo_dark: '/images/logodark.png'
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------

stats:
  marathons: 27
  countries: 75
  marathoncounties: 12
  campingcounties: 20
  wawmarkers: 100
  nwtrails: 7

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Tags"
      url: "/tags/"
    - title: "About Me"
      url: "/about/"
    - title: "Seven Summits"
      url: "/sevensummits/"
    - title: "Scratch Map"
      url: "/scratchmap/"
    - title: "Irish NWT's"
      url: "/nwt/"
    - title: "Bucket List"
      url: "/bucketlist/"
    - title: "Contact"
      url: "/contact/"

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Welcome to my Blog
  hero_description: Capturing memories from around the world. Like marathons on every continent, climbing the world’s highest peaks, backpacking over 75 countries, an Ironman triathlon, multiday hikes, whitewater kayaking, bike touring, and lots of challenges in between. This is my story, and everything I've learned along the way.
  hero_image: '/images/01.jpg'


#-------------------------------
# Newsletter
mailchimp:
  enable: false
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Subscribe here
  mailchimp_button_text: Get a new tip


#-------------------------------
# Author Settings
author:
  author_name: Brian O'Mahony
  author_bio: Irish Runner, Mountaineer, Thru-Hiker, Kayaker, Triathlete & World Traveller
  author_avatar: '/images/profile1.jpeg'


social:
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/brianom95"}
- {icon: "fa-brands fa-square-facebook", name: "Facebook", link: "https://www.facebook.com/brian.omahony.79/"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://youtube.com/@brianom95?si=bFWI82ByrMly82ie"}
- {icon: "fa-brands fa-linkedin", name: "Linked-In", link: "https://www.linkedin.com/in/brianom95?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Gallery Footer Section
gallery:
  enable: true
  gallery_title: Gallery
  gallery_columns: 3
  gallery_images:
    - alt: 'Zimbabwe'
      url: '/images/gallery1.jpeg'
    - alt: 'India'
      url: '/images/gallery2.jpeg'
    - alt: 'Argentina'
      url: '/images/gallery3.jpeg'
    - alt: 'France'
      url: '/images/gallery4.jpeg'
    - alt: 'Ireland'
      url: '/images/gallery5.jpeg'
    - alt: 'Peru'
      url: '/images/gallery6.jpeg'
    - alt: 'Bolivia'
      url: '/images/gallery7.jpeg'
    - alt: 'USA'
      url: '/images/gallery8.jpeg'
    - alt: 'Belize'
      url: '/images/gallery9.jpeg'

#-------------------------------
# Contact Settings
contact:
  form_id: xeeeaqby # Add your form_id
  description: Feel free to get in touch! # Add a description of your form

# NOTE
# Menca theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus_identifier: demo-menca # Add your shortname for Disqus Comment. For example demo-menca


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
